### PR TITLE
Refactor and separte CGO and GO parts

### PR DESCRIPTION
**Pull request by fsenart**
Use Go build tags to separte CGO and GO parts of the library. Thus when
someone needs to use only GO parts (for testing puposes, etc.) he can
disable CGO by setting the CGO_ENABLED environment variable to 0 when
running the go tool.

For example:

	CGO_ENABLED=0 go test

REF: eawsy/aws-lambda-go#9

### CODE REVIEW

**Comment by Zambiorix** [comment]
That looks perfect to me! No breaking changes :-)

When I try this, however, I get an error:
go install net: open /usr/local/go/pkg/darwin_amd64/net.a: permission denied

I have never seen this before when building my projects, any idea?

**Comment by fsenart** [comment]
@Zambiorix it seems not to be related these new changes. aws-lambda-go does not use `net`.

Maybe you have to double check your Docker image. In fact, if you haven't already a pkg/darwin_amd64 directory in your GOPATH and use the Docker image to get the dependencies of your project, then you have to set correct permissions to the newly created folders as the Docker image uses the root user by default.

**Comment by Zambiorix** [comment]
I am not sure. It is somehow related to 

`
CGO_ENABLED=0
`

As soon as I use this flag I cannot compile my projects, without it (and removing the context dependency) everything compiles fine. 

The whole idea is to only use the docker image to create a deployment package, and only for that. For testing I use my api-package and give it dummy  event and context objects. This is compiled and run outside the docker image in my regular build environment. The only thing then missing is the context object. 

So, your solution basically isolates the context object from the package with the help of CGO flag. But as soon as I use that I get above error, and only then ... Without the flag and replacing the context object by interface{}, everything compiles fine.

I am sure there is nothing wrong with your package, but the disabling the CGO flag on my development machine behaves differently, and I have to figure out why...

**Comment by fsenart** [comment]
@Zambiorix I see. 

These discussions gave me an idea. Why not push your solution further by isolating all CGO related parts into something like runtime/shim and let other things like Context, handler, etc in the runtime package. 
My idea is to isolate all stuff which should be removed by the future AWS official support and let other stuff living their life independently. 
This is kind a merge between what you've proposed and what I've refactored.

**Comment by fsenart** [comment]
@Zambiorix we should continue the discussion in the main issue thread.

**Comment by Zambiorix** [comment]
indeed ...

**Comment by Zambiorix** [comment]
I'll do some investigation in the CGO_ENABLED=0 issues on my side, in the mean time. It has something to do with permissions on GOROOT, but I do not like to touch those...

**Comment by fsenart** [comment]
I think we should definitely abandon CGO_ENABLED=0. It has global side effects. It was pretty cool to hack your problem this way but after some reflection, I think we should give up this path.

**Comment by Zambiorix** [comment]
ok, I'll wait for you to come up with the new solution :-)
I'll stop commenting here and other remarks will go to the main thread

**Pull request merged**
